### ISSUE TITLE
What are the steps to install ruby-dbi and start using My SQL in ruby script?

### ISSUE THREAD

**Issue by Mandeep10** [erikh/ruby-dbi#16]
I am using jruby 1.7.10, but while installing ruby-dbi gem, it is giving error that ruby-dbi not completely installed. Using this link, http://www.tutorialspoint.com/ruby/ruby_database_access.htm ,  I am trying step wise but its not working.

**Comment by zhuiyish** [comment]
ruby version is too old,please use ruby1.9.3.
