### ISSUE TITLE
ArgumentError: not delegated

### ISSUE THREAD

**Issue by msumit** [erikh/ruby-dbi#18]
We've been using ruby DBI since a long time with ruby-1.8.6 without any issues. Recently we switched to ruby2.1.6 and finding delegation issues to array class. 

irb(main):037:0> results.class
=> DBI::Row

irb(main):038:0> results.length
ArgumentError: not delegated
    from /usr/lib/ruby/2.1.0/delegate.rb:392:in `__getobj__'
    from /usr/lib/ruby/2.1.0/delegate.rb:341:in`block in delegating_block'
    from (irb):39
    from /usr/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
    from /usr/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in`start'
    from /usr/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by danweller18** [comment]
Ran into same issue and this solved it for me. http://stackoverflow.com/questions/27873121/dbi-row-delegate-behavior-between-ruby-1-8-7-and-2-1

Ran into the same issue, tracked down the problem.

Find lib/dbi/row.rb in the gem directory. Line 212 or thereabouts should read

            if RUBY_VERSION =~ /^1\.9/
Edit it to be

            if RUBY_VERSION =~ /^1\.9/ || RUBY_VERSION =~ /^2/

**Comment by jstoebel** [comment]
Is there any work by anyone to fork this project to incorporate this change?
