### ISSUE TITLE
Are you guys aware of any issues with temporary tables?

### ISSUE THREAD

**Issue by housekeeper** [erikh/ruby-dbi#2]
Over time my queries for a particular task have become more complicated. 
In the initial stages of the query everything worked fine. Now I use a temporary table and no results are returned!! Any idea why?

Using JRUBY, DBI, jTDS, Sybase

Any help would be much appreciated?

**Comment by matthew342** [comment]
@housekeeper Was your problem with DBI or with how you were using it? If it was with DBI would be great to see a PR to keep improving DBI :+1:
