### ISSUE TITLE
add readme note that this library is not maintained

### ISSUE THREAD

**Issue by matkoniecz** [erikh/ruby-dbi#27]
Currently it is hidden in for example https://github.com/erikh/ruby-dbi/issues/5#issuecomment-590976

**Comment by Pistos** [comment]
Done: https://github.com/erikh/ruby-dbi/commit/1c6508ce5fd2945118ec182530695164f090d860

**Comment by matkoniecz** [comment]
Thanks, that is probably the quickest reply from maintainer of no longer maintained library that I encountered :)

**Comment by erikh** [comment]
It would have taken longer if I had to do it. :)

Pistos still rocks. :D
